### ISSUE TITLE
Cannot add cookies by set method.

### ISSUE THREAD

**Issue by sharique123** [pshort/nsupertest#10]
I am unable to add cookie by set method, it adds other headers but not cookie.
var cookie = "user=abc";
Server
      .Get("/")
      .Set("Accept", "application/json")
      .Set("Cookie", cookie)
      .Expect(200)
      .End();

**Comment by pshort** [comment]
Hey thanks for the feedback, I will look into fixing this :)

**Comment by pshort** [comment]
Added httphandler to allow passing cookies in via header

**Comment by pshort** [comment]
Fix in version 0.1.22 of Nuget package
