### ISSUE TITLE
About .net core version

### ISSUE THREAD

**Issue by HX-Rd** [pshort/nsupertest#11]
Hi man, very cool that you got the .net core version going 👍 
Just a thought, maybe put it in the read me that version 2 is .net core and version 1 is the standard .net version, and or point to the different branches for the different .net versions

**Comment by pshort** [comment]
Roger that will get around to it. just trying to get appveyor to build .net core and dotnet package it, ill update the readmes

**Comment by pshort** [comment]
Closing this issue as v 3 will support multi targeting so net45 and netcoreapp2.1 targets
