### ISSUE TITLE
Error Occurred once Installed for Version 0.1.22

### ISSUE THREAD

**Issue by jonast92** [pshort/nsupertest#12]
Once the 0.1.22 version of the Nuget Package is installed it's not possible to see the Installed packages in the nuget package manager for the solution. Instead an error is displayed that says "Error occurred", and that's it.

Deleting the project and starting from scratch did not help and neither did deleting all the installed packages and re-installing them.

Downgrading to version 0.1.21 fixed the problem.

**Comment by pshort** [comment]
0x release is not supported any more, will be adding providers for .net fw in 5x release soon
