### ISSUE TITLE
Feature request: Multipart message with POST

### ISSUE THREAD

**Issue by arnorhaux** [pshort/nsupertest#13]
Hi Peter 

Would you consider adding attachments with POST messages? (multiple files)

Example

            Server
                .Post(BaseRoute)
                .Send(ValidEmailObject)
                .Attach('file1', 'test/fixtures/avatar.jpg')
                .Attach('file2', 'test/fixtures/pokeee.jpg')
                .Set(Authorization, GenerateVendorToken())
                .ExpectUnauthorized()
                .End();

**Comment by arnorhaux** [comment]
Ok, after viewing the source I see that .Send() also take MultipartFormDataContext 

Keep up the good work Peter :)

**Comment by pshort** [comment]
Haha sorry I just got round to looking at this now :) yes I think you can add multi part in send. Ironically I think it was either @gislikonrad  or Jokull who did that work :P
