### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by HX-Rd** [pshort/nsupertest#2]
I mate, great lib, use it ALL the time! What an awesome library you have created, I mean all praises. One thing, i have a feature request. I would be able to use enums in the expect method instead of the int status codes.

**Comment by pshort** [comment]
Hmmm. I didn't put in enums because I didnt like something like, .Expect(HttpStatusCode.Ok). How about instread a set of methods to let you do:

.ExpectOk()
.ExpectBadRequest()
.ExpectNoFound()

**Comment by HX-Rd** [comment]
Yupp that sounds good

**Comment by pshort** [comment]
Ok, this could snowball with not much benefit, 

Ill implement status code enum checks and a few simple overloads
