### ISSUE TITLE
Feature request, custom startup

### ISSUE THREAD

**Issue by HX-Rd** [pshort/nsupertest#3]
So I have another feature request. So instead of creating the server with the concrete Startup class of the referenced project to test, maybe we could get what class to create from a config. Some thing along these lines 
http://www.asp.net/aspnet/overview/owin-and-katana/owin-startup-class-detection

**Comment by pshort** [comment]
Ok so I'm gonna have an appSetting with the key nsupertest:appStartup. That key will be in the "{Assembly} {ClassFullName}" format that people have historically used to specify classes in .net

If you specify this then you can use a parameterless Server constructor so:

Server()

Also as I am using config I will add a parameter called nsupertest:port that will allow you to set the port for the in memory server to whatever you want (as long as its a valid port...)

**Comment by pshort** [comment]
Its in 0.1.18 💃 #

**Comment by HX-Rd** [comment]
nice nice!
