### ISSUE TITLE
Model validation

### ISSUE THREAD

**Issue by SigmarGit** [pshort/nsupertest#8]
When writing validation tests to check if properties in a model are in the correct format 
it would be nice if nsupertest could give back the returned content with a 400 bad request so it would be easy to assert in the test. 

example of returned 400 bad request
{
  "message": "The request is invalid.",
  "modelState": {
    "body.SomeCode": [
      "The field SomeCode must match the regular expression '^[A-Z]{3}'."
    ]
  }
}

**Comment by pshort** [comment]
Well that weekend came and went. Issue is now fixed :)
